version: '3'
services:

  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./cert.pem:/etc/nginx/cert.pem
      - ./privkey.pem:/etc/nginx/privkey.pem
      #- ./www:/data/www
    ports:
    - "80:80"
    - "443:443"
    
  rabbit:
    image: rabbitmq:3.8-management
    ports:   
      - "5671-5672:5671-5672"
      - "15672:15672"
      - "4369:4369"
      - "15671:15671"     

  mysql:
    image: mysql:5.7
    volumes:    
        - ./mysql.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_DATABASE: semaphore
      MYSQL_USER: semaphore
      MYSQL_PASSWORD: semaphore
    #ports:
      #- "3306:3306"
      
  semaphore:
    image: qcdis/docker_ansible_semaphore
    environment:
      SEMAPHORE_DB_USER: semaphore
      SEMAPHORE_DB_PASS: semaphore
      SEMAPHORE_DB_HOST: mysql
      SEMAPHORE_DB_PORT: 3306
      SEMAPHORE_DB: semaphore
      SEMAPHORE_PLAYBOOK_PATH: /etc/semaphore
      SEMAPHORE_ADMIN_PASSWORD: password
      SEMAPHORE_ADMIN_NAME: "Developer"
      SEMAPHORE_ADMIN_EMAIL: admin@localhost
      SEMAPHORE_ADMIN: admin
      SEMAPHORE_WEB_ROOT: http://0.0.0.0:3000
    ports:
      - "3000:3000"
    depends_on:
      - mysql
      
  mongo:
    image: mongo:4
    ports:
      - "27017:27017"  
      
  mongo-express:
    image: mongo-express
    environment:
        - ME_CONFIG_MONGODB_SERVER=mongo
        - ME_CONFIG_MONGODB_PORT=27017
        - ME_CONFIG_BASICAUTH_USERNAME=user
        - ME_CONFIG_BASICAUTH_PASSWORD=pass
        - ME_CONFIG_SITE_BASEURL=/mongo-express
        - VCAP_APP_PORT=8082
    depends_on:
        - mongo
    ports:
        - "8082:8082"    
        
        
  #mongoclient:
    #image: mongoclient/mongoclient
    #environment:
        #- MONGO_URL=mongodb://mongo:27017
        #- ROOT_URL=http://mongoclient/mongoclient
    #depends_on:
        #- mongo
    #ports:
        #- "3001:3000"            
        
      
  #manager:
    #depends_on:
      #- rabbit
      #- mongo
      #- sure-tosca
    #image: qcdis/manager 
    #environment:
      #RABBITMQ_HOST: rabbit
      #MONGO_HOST: mongo
      #SURE_TOSCA_BASE_PATH: http://sure-tosca:8081/tosca-sure/1.0.0
      #CREDENTIAL_SECRET: top_secret
    #ports:
      #- "8080:8080"       
            
  sure-tosca:
    image: qcdis/sure-tosca
    ports: 
      - "8081:8081"
    
  planner:
    depends_on:
      - rabbit
      - sure-tosca
    image: qcdis/planner 
    environment:
      RABBITMQ_HOST: rabbit
    
  provisioner:
    depends_on:
      - rabbit
      - sure-tosca
    image: qcdis/provisioner 
    environment:
      RABBITMQ_HOST: rabbit      
      SURE_TOSCA_BASE_PATH: http://sure-tosca:8081/tosca-sure/1.0.0
      CLOUD_STORM_SECRET: 456
      CREDENTIAL_SECRET: top_secret
    
  deployer:
    depends_on:
      - rabbit
      - sure-tosca
    image: qcdis/deployer 
    environment:
      RABBITMQ_HOST: rabbit           
      SURE_TOSCA_BASE_PATH: http://sure-tosca:8081/tosca-sure/1.0.0
      SEMAPHORE_BASE_PATH: http://semaphore:3000/api
      
  cadvisor:
    image: gcr.io/google-containers/cadvisor:latest
    ports:
    - 8083:8080
    volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro
    
      
