apiVersion: v1
kind: Service
metadata:
  labels:
    app: NAME
  name: NAME
  namespace: default
spec:
  type: NodePort
  ports:
    - port: CONTAINER_PORT
      nodePort: NODE_PORT
  selector:
    app: NAME
